# POST http://localhost:3000/post HTTP/1.1
# Content-Type: application/json

# {
#     "name": "fuck",
#     "age": "18",
#     "dirty": true
# }

# GET http://localhost:3000/form?name="fuck"&call="shit"


# POST http://localhost:3000/send/mail HTTP/1.1
# Content-Type: application/json

# {
#     "to": "123@qq.com",
#     "subject": "标题",
#     "text": "我想你了，你还好吗？"
# }

# GET http://localhost:3000/form/96


# POST http://localhost:3000/user/login HTTP/1.1
# Content-Type: application/json

# {
#     "name": "xigua",
#     "pass": "123456"
# }

# GET http://localhost:3000/ HTTP/1.1

# GET http://localhost:3000/user/14 HTTP/1.1


#  POST http://localhost:3000/add HTTP/1.1
# Content-Type: application/json

# {
#     "name": "西施", 
#     "age": 18, 
#     "address": "浣溪沙", 
#     "hobby": "商业间谍", 
#     "gender": 0
# }

# POST http://localhost:3000/add HTTP/1.1
# Content-Type: application/json

# {
#     "name": "眼睛蛇", 
#     "age": 3, 
#     "address": "蛇坑", 
#     "hobby": "老鼠", 
#     "gender": 0
# }#

# POST http://localhost:3000/add HTTP/1.1
# Content-Type: application/json

# {
#     "name": "米老鼠", 
#     "age": 2, 
#     "address": "大漂亮国", 
#     "hobby": "猫", 
#     "gender": 1
# }

# POST http://localhost:3000/update HTTP/1.1
# Content-Type: application/json

# {
#     "id": 15, 
#     "hobby": "搞死吴国"
# }

# POST http://localhost:3000/update HTTP/1.1
# Content-Type: application/json

# {
#     "id": 10, 
#     "hobby": "闲适的生活"
# }

DELETE http://localhost:3000/delete HTTP/1.1
Content-Type: application/json

{
    "id": 16
}